name: CI SNAPSHOT

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - '*.x'

jobs:
  build_snapshot:
    uses: spring-io/spring-github-workflows/.github/workflows/spring-artifactory-maven-snapshot.yml@main
    secrets:
      ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
      ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}